-- ORDER OF INITIALIZATION
require 'm.plugins'
require 'm.sets'
require 'm.maps'
require 'm.highlight'
require 'm.lsp'
require 'm.tree'
require 'm.completion'
require 'm.colors'
-- require 'm.status'
require 'm.finder'
require 'm.latex'
-- require 'm.norg'
-- require 'm.parsers'
