local o = vim.opt
o.gcr = ''
o.cul = true
o.nu = true
o.rnu = true
o.mouse = 'a'
o.ruler = false
o.hidden = true
o.hlsearch = false
o.showcmd = false
o.showmode = false
o.cmdheight = 1
o.tabstop = 2
o.shiftwidth = 2
o.softtabstop = 2
o.expandtab = true
o.ai = true
o.smarttab = true
o.wrap = false
o.signcolumn = 'number' -- 'no'|'number'
o.updatetime = 500
o.timeoutlen = 360
o.smartcase = true
o.ignorecase = true
o.incsearch = true
o.completeopt = 'menuone,noselect'
o.backup = false
o.undofile = true
o.foldmethod = 'manual'
o.laststatus = 1 -- 0 is none
-- o.scrolloff = 5
