local o, cmd = vim.opt, vim.cmd
o.mouse = 'a'
o.nu = true
o.relativenumber = true
o.ruler = false
o.hidden = true
o.showcmd = false
o.showmode = false
o.showmatch = false
o.cmdheight = 1
o.statusline = '%t %y%(%8*%m%1*%)'
o.tabstop = 2
o.shiftwidth = 2
o.softtabstop = 2
o.wrap = false
o.expandtab = true
o.signcolumn = 'yes'
o.updatetime = 27
o.timeoutlen = 500
o.smartcase = true
o.ignorecase = true
o.incsearch = true
o.completeopt = 'menuone,noselect'
o.backup = false
o.undofile = true
-- COLORS
o.termguicolors = true
o.background = 'dark'
cmd 'colorscheme melange'
